#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="generate-api"
SCRIPT_DES=$'Process the application modules into toctrees'
PROJECT_DIR=$SCRIPT_DIR/../..
ENV_DIR=$PROJECT_DIR/env
source $ENV_DIR/.env

sphinx-apidoc -o $PROJECT_DIR/docs/source $PROJECT_DIR/src/innoldb
