#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="generate-api"
SCRIPT_DES=$'Process the application modules into toctrees'
PROJECT_DIR=$SCRIPT_DIR/../..

cd $PROJECT_DIR/docs

make html