#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="qldb-stack"
SCRIPT_DES=$'A script for posting a template of QLDB service to CloudFormation. See comments in script for usage information.'
PROJECT_DIR=$SCRIPT_DIR/../..
source $PROJECT_DIR/env/.env

# Example Usage:
# >$     qldb-stack --ledger <ledger-name> --help 

function log(){
  echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
  echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --ledger|-ledger|--l|-l)
      # Name of the ledger that will be stood up on AWS
      LEDGER_INPUT="$2"
      shift
      shift 
      ;;
    --help|-help|--h|-h)
      help
      exit 0
      ;;
    *)
      log "Input not understood. See \e[3m--help\e[0m for information on using this command."
      exit 1
      ;;
  esac
done

if [ -z "$LEDGER_INPUT" ]
then
  log "No \e[3m--ledger\e[0m specified. Default to \e[2mLEDGER\e[0m environment variable."
  if [ -z "$LEDGER"]
  then
    log "No ledger found. Re-execute this script with an argument or configure your environment."
    exit 1
  else
    LEDGER_INPUT=$LEDGER
  fi
fi

log "Creating \e[1m${LEDGER_INPUT^}-QLDB-Stack\e[0m"
aws cloudformation create-stack \
    --stack-name "${LEDGER_INPUT^}-QLDB-Stack" \
    --template-body file://qldb.yml \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameters ParameterKey=ledgerName,ParameterValue="${LEDGER_INPUT}"
