#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="install"
SCRIPT_DES=$'Build and install the \e[3mqldb-orm\e[om from source.'
PROJECT_DIR=$SCRIPT_DIR/..
source $PROJECT_DIR/env/.env

cd $PROJECT_DIR

coverage run --source="." \
              --omit="**/test_*.py","**/__init__.py" \
              --module pytest \
                        --junit-xml=./docs/coverage/coverage-execution.xml
coverage xml -o ./docs/coverage/coverage.xml
coverage html --dir=./docs/coverage